linters:
  enable-all: true
  disable:
    - lll
    - varnamelen
    - exhaustivestruct
    - exhaustruct
    - godox
    - nlreturn
    - wsl
    - wrapcheck
    - gochecknoglobals
    - paralleltest
    - dupl
    - golint
    - maligned
    - gci
    # deprecated/archived
    - interfacer
    - scopelint
    - nosnakecase
    - varcheck
    - structcheck
    - deadcode
    - ifshort
issues:
  include:
    - EXC0002
    - EXC0011
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
  exclude:
    - "returns unexported type"
    - "unlambda"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - goerr113
        - funlen
        - godot
        - dupl
        - gocognit
        - cyclop
        - noctx
        - maintidx
        - gosec
        - gocyclo
    - path: _exports_test\.go
      linters:
        - testpackage
    - path: cmd/*
      linters:
        - funlen
    - path: internal/*
      linters:
        - goerr113
        - nonamedreturns
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: camel
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
  cyclop:
    max-complexity: 15
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - "github.com/dop251/goja.Value"
run:
  go: "1.19"
