name: Tests

on:
  push:
    branches:
      - main
  pull_request:
env:
  GOPRIVATE: "github.com/speakeasy-api"
jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go-version: [1.19.x]

    name: Tests - Go ${{ matrix.go-version }}

    steps:
      - name: Configure git for private modules
        env:
          GIT_AUTH_TOKEN: ${{ secrets.BOT_REPO_TOKEN }}
        run: git config --global url."https://speakeasybot:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run the tests
        run: go test ./...
